#! /bin/bash
test -f ../../wxDownloadFast-0.70.3.dmg && rm ../../wxDownloadFast-0.70.3.dmg
    create-dmg \
            --window-size 500 300 \
            --background ./background.png \
            --text-size 14 \
            --icon-size 128 \
            --volname wxDownloadFast-0.70.3 \
            --volicon ../resources/RipStop/icon/wxdfast.icns \
            --icon wxDownloadFast.app 125 150 \
            --app-drop-link 385 150 \
        ../../wxDownloadFast-0.70.3.dmg \
        ../build-release
